development:
  adapter: postgresql
  encoding: unicode
  database: pipo_development
  pool: 5
  username: postgres
  password: 3131567у

test:
  adapter: postgresql
  encoding: unicode
  database: pipo_test
  pool: 5
  username: postgres
  password: 3131567у